version: 2.1

jobs:
  build:
    docker:
      - image: python:3.11

    working_directory: /app

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: pip install -r requirements.txt

      - run:
          name: Run tests
          command: python -m pytest

      - persist_to_workspace:
          root: /app
          paths:
            - .

  deploy:
    docker:
      - image: python:3.11

    working_directory: /app

    steps:
      - attach_workspace:
          at: /app

      - run:
          name: Deploy container
          command: |
            docker build -t predict-app:latest .
            docker run -d -p 80:80 predict-app:latest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
